### ISSUE TITLE
Issue with compile at x86

### ISSUE THREAD

**Issue by slipros** [G-E-N-E-S-I-S/nt-mapper#1]
Hey, i have error when i compile at x86 at file portable_executable.cpp
`this->nt_headers = reinterpret_cast<IMAGE_NT_HEADERS64*>(this->buffer.data() + this->dos_header->e_lfanew);`
This is what fix this issue, but is it valid fix?
`this->nt_headers = reinterpret_cast<IMAGE_NT_HEADERS*>(this->buffer.data() + this->dos_header->e_lfanew);`

Thank you

**Comment by vmcall** [comment]
It's a 64 bit mapper you mongoloid
